version: '3'

# need to be seen by server too for CORS
env:
  CLIENT_PORT: 8888 
  SERVER_PORT: 3000 
  URL: "http://localhost"

tasks:
  # Vite requires env variables to have a 
  # special name (VITE_ prefix) and to be in a .env file
  config-client:
    cmds:
      - | 
        npm install
        echo "VITE_URL=$URL" > .env
        echo "VITE_SERVER_PORT=$SERVER_PORT" >> .env
    generates:
      - .env
    dir: ./vue/

  build-server:
    cmds:
      - | 
        go build -o server . 
        echo "Built server binary"
    dir: ./server/
    generates:
      - server

  server:
    # Compiled binary is 5MBs, won't push to Git
    deps:
      - build-server
    desc: Run the Golang server binary
    cmds:
      - ./server
    dir: ./server/

  client:
    desc: Run the vue client, server port is hardcoded in App.vue
    deps:
      - config-client
    cmds:
      - npm run dev -- --port $CLIENT_PORT --host
    dir: ./vue/

  run:
    deps:
      - server
      - client
