version: '3'

# need to be seen by server too for CORS
env:
  CLIENT_PORT: 8888 
  URL: "http://127.0.0.1"

tasks:
  build-server:
    cmds:
      - | 
        if [ ! -f server ]; then 
          go build -o server . 
          echo "Built server binary"
        fi
    dir: ./server/
    generates:
      - server

  server:
    # Compiled binary is 5MBs, won't push to Git
    deps:
      - build-server
    desc: Run the Golang server binary
    env: 
      SERVER_PORT: 3000 
    cmds:
      - ./server
    dir: ./server/

  client:
    desc: Run the vue client, server port is hardcoded in App.vue
    cmds:
      - npm install && npm run dev -- --port $CLIENT_PORT --host
    dir: ./vue/

  run:
    deps:
      - server
      - client
